# Placeholder for manual deploy script. Included for training purposes

name: .Deploy to Production
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version number (optional)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug github
      env:
        CONTEXT: ${{ toJSON(github) }}
      run: echo "$CONTEXT"
    - name: Deploy
      run: echo Deploy to production
