# Placeholder for manual deploy script. Included for training purposes

name: .Deploy to Production
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version number (optional)'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.version_number }}

    - name: Deploy
      run: echo Deploy to production
