# Builds and deploys to firebase hosting preview channel.

name: Preview pull request
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  # issue_comment:
  #   types: [created, edited]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"

  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check_preview_develop
        with:
          trigger: 'preview:develop'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: View output
        run: echo "Output - ${{ toJSON(steps.check_preview_develop.outputs) }}"
      - name: Preview develop
        if: steps.check_preview_develop.outputs.triggered
        run: echo Preview develop

