name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Update release notes
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: Update package version
        #run: echo "Draft release version number is ${{ steps.release_drafter.outputs.tag_name }}"
        run: npm version ${{steps.release_drafter.outputs.tag_name}} -m "Bump version number to %s"

      # # Use this GitHub Action
      # - name: Check package version
      #   uses: technote-space/package-version-check-action@v1
      #   with:
      #     NEXT_VERSION: steps.release_drafter.outputs.tag_name
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
