name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'package-lock.json'

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.DEPLOY_TOKEN }}'

      - name: Check package version
        id: package_version
        run: echo "::set-output name=current_version::$(node -p "require('./package.json').version")"

      - name: Bump package version
        if: steps.package_version.outputs.current_version != '1.0.6'
        run: |
          echo "Bump package version from ${{ steps.package_version.outputs.current_version }} to 1.0.6"
          npm version patch -m "Bump version number to %s"
          node -p "require('./package.json').version"


      # - name: Update package version
      #   #run: echo "Draft release version number is ${{ steps.release_drafter.outputs.tag_name }}"
      #   run: npm version patch -m "Bump version number to %s"
      # - name: Display
      #   run: node -p "require('./package.json').version"

      # # Drafts your next Release notes as Pull Requests are merged into "master"
      # - name: Update release notes
      #   id: release_drafter
      #   uses: release-drafter/release-drafter@v5
      #   with:
      #     config-name: release-drafter.yml
      #     disable-autolabeler: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}


      # # Use this GitHub Action
      # - name: Check package version
      #   uses: technote-space/package-version-check-action@v1
      #   with:
      #     NEXT_VERSION: steps.release_drafter.outputs.tag_name
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
